#!/usr/bin/make -f
# Waf Makefile wrapper

all:
	cd .. && /home/enrico/projects/sion/trunk/waf build

all-debug:
	cd .. && /home/enrico/projects/sion/trunk/waf -v build

clean:
	cd .. && /home/enrico/projects/sion/trunk/waf clean

