#!/usr/bin/make -f
# Waf Makefile wrapper
WAF_HOME=/home/enrico/projects/sion

all:
	cd .. && /home/enrico/projects/sion/waf build

all-debug:
	cd .. && /home/enrico/projects/sion/waf -v build

clean:
	cd .. && /home/enrico/projects/sion/waf clean

